# Generated by Django 6.0.6 on 2026-07-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={},
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção'), ('oleo', 'Troca de Óleo'), ('pneu', 'Pneus'), ('lavagem', 'Lavagem'), ('combustivel', 'Combustível'), ('seguro', 'Seguro'), ('ipva', 'IPVA'), ('licenciamento', 'Licenciamento'), ('multa', 'Multa'), ('guincho', 'Guincho'), ('pecas', 'Peças'), ('acessorios', 'Acessórios'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='gestao.veiculo')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data'],
            },
        ),
    ]
