# Generated by Django 6.0.6 on 2026-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_pagamento_options_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='periodicidade_dias',
            field=models.IntegerField(default=8, help_text='A cada quantos dias o pagamento se renova (padrão: 8 dias)'),
        ),
    ]
