# Generated by Django 5.2.15 on 2026-07-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_locacao_periodicidade_dias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['nome', 'modelo'], 'verbose_name': 'Veículo'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='categoria_cnh',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='foto_cnh',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='validade_cnh',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='quilometragem',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='renavam',
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_documento',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/documentos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='nome',
            field=models.CharField(default='', help_text='Ex: Onix, HB20, Civic', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(help_text='Ex: LT, Sense, EXL', max_length=100),
        ),
    ]
