# Generated by Django 5.2.15 on 2026-07-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_veiculo_options_remove_cliente_categoria_cnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='periodicidade_dias',
            field=models.IntegerField(choices=[(7, 'A cada 7 dias'), (8, 'A cada 8 dias'), (15, 'A cada 15 dias'), (30, 'A cada 30 dias')], default=8),
        ),
    ]
