# Generated by Django 5.2.15 on 2026-07-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_locacao_periodicidade_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='data_inicio_real',
            field=models.DateField(blank=True, help_text='Preencha só se o cliente já está com o carro há mais tempo do que a data de retirada cadastrada', null=True),
        ),
    ]
