# Generated by Django 5.2.15 on 2026-08-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_peca'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('cliente',), name='unique_locacao_ativa_por_cliente'),
        ),
    ]
